/**
 * Splits a secret into a set of shares using Shamir's Secret Sharing Scheme.
 * Compatible with the original ssss-split from point-at-infinity.org/ssss/.
 *
 * @param buf - The secret string to split.
 * @param params - Parameters for splitting the secret.
 * @param params.threshold - The minimum number of shares needed to reconstruct the secret.
 * @param params.inputIsHex - If true, the input secret is interpreted as a hexadecimal string.
 * @param params.prefix - Optional prefix for each share to uniquely identify shares of this secret from shares of another secret. Should not use the character '-'
 * @param params.numberOfKeys - The total number of shares to generate.
 * @param options - Additional options for entropy export/customization.
 * @param options.useCustomEntropy - If true, the custom entropy string is used instead of the default entropy.
 * @param options.entropy - The custom entropy string to use instead of the default entropy.
 * @param options.exportEntropy - If true, exports the entropy used for generating shares.
 * @returns Returns an array containing the generated shares.
 */
export function split(
  buf: string,
  params: {
    threshold: number;
    inputIsHex?: boolean;
    prefix?: string;
    numberOfKeys: number;
  },
  options?: {
    useCustomEntropy?: boolean;
    entropy?: string;
    exportEntropy?: boolean;
  }
): string[];

/**
 * Combines a set of shares to recover a secret using Shamir's Secret Sharing Scheme.
 *
 * @param shares - An array of share strings to be combined.
 *   Each share must be in the format generated by the split function.
 * @param params - Parameters for secret reconstruction.
 * @param params.threshold - The minimum number of shares needed to reconstruct the secret.
 * @param params.inputIsHex - If true, the reconstructed secret will be returned as a hexadecimal string.
 * @returns The recovered secret string (hex or utf-8 depending on inputIsHex).
 */
export function combine(
  shares: string[],
  params: {
    threshold: number;
    inputIsHex?: boolean;
  }
): string;

/**
 * Generates a new set of shares from an existing set of shares. This is useful for
 * resplitting a secret after threshold recovery, often called re-keying or extending.
 * The recovered secret is not exposed directly in this process.
 *
 * @param shares - Array of share strings (must be at least threshold length).
 * @param params - Parameters for resplitting.
 * @param params.threshold - Minimum number of shares needed to reconstruct the secret. Must be less than numberOfKeys.
 * @param params.inputIsHex - If true, the shares/secret are in hexadecimal format.
 * @param params.prefix - Optional prefix used for all new shares.
 * @param params.numberOfKeys - The number of new shares to generate.
 * @returns An array of newly generated shares
 */
export function resplit(
  shares: string[],
  params: {
    threshold: number;
    inputIsHex?: boolean;
    prefix?: string;
    numberOfKeys: number;
  }
): string[];

/**
 * Parses a single Shamir share string into its components (prefix, index, value).
 * A share is typically formatted as "prefix-index-value", where each part is delimited by "-".
 * The prefix is optional; if the share has only index and value, prefix is undefined.
 *
 * @param share - The encoded share string.
 *     Expected format: "[prefix-]index-value" (prefix is optional, index is an integer, value is field data as a string).
 * @returns An object containing the optional prefix, the numeric index, and the value part of the share.
 */
export function parseShare(share: string): {
  prefix: string | undefined;
  index: number;
  value: string;
};
